sudo: false
language: ruby
rvm: ruby-2.3.4
dist: trusty
env:
  - TYPE="rubocop" TEST_COMMAND="bundle exec rubocop"
  - TYPE="test" TEST_COMMAND="bundle exec rake test TESTOPTS=-v"
script:
  - (eval "$TEST_COMMAND")