task default: :test

task :test do
  ruby 'test/1_*.rb'
  ruby 'test/2_*.rb'
  ruby 'test/3_*.rb'
  ruby 'test/9_*.rb'
  ruby 'test/12_*rb'
  ruby 'test/13_*rb'
  ruby 'test/14_*rb'
  ruby 'test/17_*rb'
  ruby 'test/19_*.rb'
  ruby 'test/20_*.rb'
  ruby 'test/21_*.rb'
  ruby 'test/26_*.rb'
  ruby 'test/27_*.rb'
  ruby 'test/28_*.rb'
  ruby 'test/70_*.rb'
  ruby 'test/75_*.rb'
  ruby 'test/83_*.rb'
  ruby 'test/167_*.rb'
  ruby 'test/369_*.rb'
  ruby 'test/746_*.rb'
  ruby 'test/860_*.rb'
  ruby 'test/867_*.rb'
  ruby 'test/876_*.rb'
  ruby 'test/884_*.rb'
  ruby 'test/885_*.rb'
  ruby 'test/888_*.rb'
  ruby 'test/896_*.rb'
  ruby 'test/900_*.rb'
  ruby 'test/901_*.rb'
end
